app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, FloatField, SubmitField, DateField, BooleanField
from wtforms.validators import DataRequired, Email, Length
from datetime import datetime


class DateForm(FlaskForm):
    today = datetime.today()
    d = DateField("Choose a date", id='dp', default=today)
    submit = SubmitField("Submit")

app/profile_settings/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, Length, Regexp


class ProfileForm(FlaskForm):
        name = StringField(label="Name",
                           validators=[DataRequired(),
                                       Regexp('^[A-Za-z][A-Za-z0-9_]*$', 0,
                                              message='User names must only have '
                                                      'letters, numbers or underscores'),
                                       Length(1, 128)],
                           id="ww-profile-name")
        email = StringField(label="Email")
        password = PasswordField(label="Password",
                                 render_kw={"placeholder": "***********",
                                            "readonly class": "form-control-plaintext"})
        submit = SubmitField(label="Submit", id="ww-profile-submit")

        def populate_placeholders(self, user):
            self.name.render_kw = {"placeholder": user.name,
                                   "readonly class": "form-control-plaintext"}
            self.email.render_kw = {"placeholder": user.email,
                                    "readonly class": "form-control-plaintext"}

app/__init__.py
"""This is the core of the Flask application. This file defines
the app factory function and some other helper stuff that will
create the app instances according to the specifications in config.py"""

# imports
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_datepicker import datepicker
from config import config

# instantiate empty instances of flask extensions
bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()
login_mgmt = LoginManager()
login_mgmt.login_view = 'auth.login'


# this is the app factory function
def create_app(config_name):
    # init app with package name
    app = Flask(__name__)
    # import the app config from a config class
    app.config.from_object(config[config_name])
    # call the init_app function in the config class
    config[config_name].init_app(app)

    # since the app is now initiated and configured, add extensions to it
    bootstrap.init_app(app)
    moment.init_app(app)
    mail.init_app(app)
    db.init_app(app)
    login_mgmt.init_app(app)

    # add datepicker and configure it
    dp = datepicker(app)
    datepicker.picker(dp, id='.dp', maxDate='2019-12-01', minDate='2019-01-01', btnsId='dpbtn')

    # only now can we import the blueprints that will use the app instance
    from .main import main as main_bp
    app.register_blueprint(main_bp)
    from .auth import auth as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')
    from .profile_settings import profile_settings as profile_settings_bp
    app.register_blueprint(profile_settings_bp, url_prefix='/profile_settings')

    return app

app/main/__init__.py
from flask import Blueprint


# Blueprints generally are placed inside the __init__.py files
# create a new Blueprint instance to register the predefined views and errors

main = Blueprint('main', __name__)

from . import errors, views

app/main/views.py
from flask import render_template, session, redirect, url_for, current_app, flash, request
from flask_login import login_required, login_user
from .. import db
from ..db_models import Measurement, User
from ..email import send_email
from . import main
from .forms import DateForm
from ..auth.forms import LoginForm


# from .plots import plot_png


@main.route('/', methods=['GET', 'POST'])
def index():
    date_form = DateForm()
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            flash("I don't know you! No user with this email account registered.")
        elif user is not None and not user.verify_password(form.pswrd.data):
            flash("Incorrect password!")
        elif user is not None and user.verify_password(form.pswrd.data):
            login_user(user, form.keep_me.data)
            next = request.args.get('next')
            if next is None or not next.startswith('/'):
                next = url_for('main.user_dash', user_id=user.id)
            return redirect(next)
        else:
            redirect('main.internal_server_error')
    else:
        for error in form.errors.items():
            flash("Something went wrong in {f} field: {m}".format(
                f=error[0], m=error[1][0]))
    return render_template('index.html', login_form=form, date_form=date_form)


@main.route('/plot')
@login_required
def plot_page():
    return render_template('base.html')


@main.route('/<user_id>/dashboard', methods=['GET', 'POST'])
@login_required
def user_dash(user_id):
    uid = user_id
    name = User.query.filter_by(id=uid).first().name
    return render_template('dashboard.html', name=name, uid=uid)

app/profile_settings/__init__.py
from flask import Blueprint

profile_settings = Blueprint('profile_settings', __name__)

from . import views

app/profile_settings/views.py
from flask import render_template, url_for
from flask_login import login_required, current_user
from app.db_models import User
from . import profile_settings
from .forms import ProfileForm


@profile_settings.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    user = User.query.filter_by(id=current_user.id).first()
    profile_form = ProfileForm()
    profile_form.populate_placeholders(user=user)
    return render_template('profile_settings/settings.html', user=user, profile_form=profile_form)

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}WeightWhat{% endblock %}

{% block head %}
    {{ super() }}
    <meta name="author" content="Maciej Cisowski (KnifeyMoloko)">
    <meta name="description" content="The little app for tracking users' weight.">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Coiny" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Chango" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Monofett" rel="stylesheet">
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" type="text/css">
{% endblock %}

{% block body %}
    {% block navbar %}
        {{ super() }}
        <nav class="navbar navbar-expand-lg navbar-dark ww-navbar">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <img src="/static/img/WWWordArt_small.png" alt="weight_what brand icon">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navCollapse"
                    aria-controls="navCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse ww-navbar-collapse" id="navCollapse">
                <ul class="navbar-nav ml-auto">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active ww-nav-item-active" href="#">
                                Add measurement
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active ww-nav-item-active" href="#">
                                See Your Results
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active ww-nav-item-active" href="{{ url_for('profile_settings.profile') }}">
                                Your profile
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active ww-nav-item-active" href="{{ url_for('auth.logout') }}">
                                Log Out
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link disabled ww-nav-item-disabled" href="#" aria-disabled="true">
                                Add measurement
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled ww-nav-item-disabled" href="#" aria-disabled="true">
                            See Your Results
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled ww-nav-item-disabled" href="#" aria-disabled="true">
                            Your profile
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active ww-nav-item-active" href="{{ url_for('main.index') }}"
                            aria-disabled="false">
                                Log In
                            </a>
                        </li>
                {% endif %}
                </ul>
            </div>
        </nav>

        <div class="container ww-flash-container">
            {% for message in get_flashed_messages() %}
                <div class="alert alert-light">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endblock %}

    {% block body_content %}
        <section class="ww-main-section"></section>
    {% endblock %}

    {% block scripts %}
        {{ super() }}
        {{ moment.include_moment() }}
        {{ datepicker.loader() }}
        <script type="text/javascript">
        $(function () {
            $('#dp').datepicker();
        });
        </script>
    {% endblock %}
{% endblock %}

app/templates/dashboard.html
{% extends 'base.html' %}

{% block body_content %}
<h1>This where the user dashboard will be.</h1>
    <h1>You are {{ name }}</h1>
    <h2>Your id is {{ uid }}</h2>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}Weight What?{% endblock %}

{% block body_content %}
    <section>
        <div class="container-fluid ww-main-index">
            <div class="row">
                <div class="col-lg-7">
                    <img class="ww-main-logo" src="{{ url_for('static', filename='img/WWWordArt_large.png') }}" alt="WordArtLogo" type="png">
                </div>
                <div class="col-lg-5 ww-login-container">
                    <div class="ww-login-form align-content-center">
                        {{ wtf.quick_form(login_form, id='log-form') }}
                        <button type='button' class="btn btn-primary btn-lg" value="reg_button"
                                id="login-register"
                                onclick="window.location.href='{{ url_for('auth.register') }}';">Register
                        </button>
                        <div class="date-choice">
                        {{ wtf.quick_form(date_form, id='datepick') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

app/templates/plot.html
{% extends "base.html" %}

{% block body_content %}
    <img src='{{ img }}' alt="myplot">
{% endblock %}

app/templates/profile_settings/settings.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}
    WeightWhat - Profile Settings
{% endblock %}

{% block body_content %}
<section>
<div id="ww-profile-container" class="container-fluid">
    <div class="row">
        <h1 id="ww-profile-h1">Your WeightWhat Profile</h1>
    </div>
    <div class="row">
        <div class="col-xl-2 col-lg-3 col-md-12 col-sm-12">
            <img id='ww-profile-portrait'
                 src="{{ url_for('static',
                 filename='img/mr_Creosote_no_bg.png') }}"/>
        </div>
        <div id="ww-profile-data" class="col-xl-10 col-lg-9 col-md-12 col-sm-12">
        <form method="POST" action="/" class="form-group">
            <div class="form-row">
                <label class="col-form-label col-lg-2 ww-profile-label">
                    {{ profile_form.name.label }}
                </label>
                <div class="col-lg-6 ww-profile-field">
                    {{ profile_form.name }}
                </div>
                <div class="col-lg-4">
                    <button type="button" class="btn-primary ww-profile-btn"
                            id="ww-profile-name-btn" onclick="activateNameField()">
                        Edit
                    </button>
                </div>
            </div>
            <div class="form-row">
                <label class="col-form-label col-lg-2 ww-profile-label">
                    {{ profile_form.email.label }}
                </label>
                <div class="col-lg-6 ww-profile-field">
                    {{ profile_form.email }}
                </div>
                <div class="col-lg-4">
                    <button type="button" class="btn-primary ww-profile-btn">
                        Edit
                    </button>
                </div>
            </div>
            <div class="form-row">
                <label class="col-form-label col-lg-2 ww-profile-label">
                    {{ profile_form.password.label }}</label>
                <div class="col-lg-6 ww-profile-field">
                    {{ profile_form.password }}
                </div>
                <div class="col-lg-4">
                    <button type="button" class="btn-primary ww-profile-btn">
                        Edit
                    </button>
                </div>
            </div>
            <div class="form-row">
                <div hidden>{{ profile_form.submit }}</div>
            </div>
        </form>
        </div>
    </div>
</div>
</section>

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript"
            src="{{ url_for('static',
            filename='JS/profileSettings.js') }}">
    </script>
{% endblock %}

templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" type="text/css">
{% endblock %}

{% block body %}
    {{ super() }}
    {% block body_content %}
    {% endblock %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ datepicker.loader() }}
    <script type="text/javascript">
    $(function () {
        $('#dp').datepicker();
    });
    </script>
{% endblock %}